### ISSUE TITLE
New page not working

### ISSUE THREAD

**Issue by alexandre1985** [michal-h21/tex4ebook#100]
I am able to create a epub file.

In the pages after my cover page, I am unable to set a new page. They are all put in sequence, without page breaks. On my pdf the output is correct.

The new page commands that I am using is:
```
\clearpage
\newpage
first page text
\vfill

\clearpage
\newpage
second page text
\vfill
```

Please help. I have a deadline on my book. Sorry...

**Comment by ivanistheone** [comment]
Do you maybe want `\clearpage` instead of `/clearpage` maybe?   Same for `\newpage` instead of `/newpage`.

There is also `\cleardoublepage` you can try (like clear page but makes sure next page is on the right)

**Comment by alexandre1985** [comment]
Yes, I want that. I sorry for the misspell. In my book I am using `\clearpage`, etc.

My problem persists.

**Comment by michal-h21** [comment]
In theory, this configuration file should work:
```

\Preamble{xhtml}
\Configure{newpage}{\ifvmode\IgnorePar\fi\EndP\HCode{<div class="newpage"></div>}}
\Css{.newpage{page-break-before:always;}}
\begin{document}
\EndPreamble
```

I had similar question [some time ago](https://tex.stackexchange.com/a/311387/2891), and proposed a special command instead of `\newpage` or `\clearpage`, because I experienced issues with some commands that use `\newpage` internally. But if you don't run into this problems, this configuration should work. For some reason, it doesn't work in Calibre, but it can be a bug in viewer.

**Comment by alexandre1985** [comment]
> ``` 
> \Preamble{xhtml}
> \Configure{newpage}{\ifvmode\IgnorePar\fi\EndP\HCode{<div class="newpage"></div>}}
> \Css{.newpage{page-break-before:always;}}
> \begin{document}
> \EndPreamble
> ```

pdflatex doesn't compile with this commands. It gives me
```
! Undefined control sequence.
l.110 \Preamble
               {xhtml}
```

**Comment by alexandre1985** [comment]
I got it. Thank @michal-h21 , it worked.

I have to put that code in a `*.cfg` file and run: `tex4ebook -f epub3 -c main.cfg main.tex`
