### ISSUE TITLE
Image displaying as (?) in Apple Books

### ISSUE THREAD

**Issue by hendricius** [michal-h21/tex4ebook#106]
I was having an issue that sometimes some of the images in Apple Books are not properly displayed, they are just shown as a `?`.

<img width="529" alt="image" src="https://github.com/michal-h21/tex4ebook/assets/816859/9d95909f-5610-4d07-a012-8a621baf465a">

I created a small sample repo where you can reproduce the bug: https://github.com/hendricius/apple-books-image-issue/blob/main/book.tex

It seems that the problem was my `graphicspath`.

This does not work:
```
\graphicspath{
  {./images/}
}
```

Changing it to the following will solve the issue:
```
\graphicspath{
  {images/}
}
```

I had previously reported this on my own repo: https://github.com/hendricius/the-sourdough-framework/issues/59. Just leaving this here in case someone else has the same issue.

Thanks Michal for the great work!

**Comment by michal-h21** [comment]
@hendricius ah sorry that I forgot about your request, I was really overwhelmed at that time. It is much better now. 

It seems like the issue reported recently on TeX.sx: https://tex.stackexchange.com/a/683436/2891. The leading dot too caused the issue here. The problem is that web browsers and some readers support it, but others do not, so it is difficult to debug it.

Do you have any other issues with the conversion to Epub?

**Comment by michal-h21** [comment]
@hendricius ah, that's strange! I cannot reproduce this error on my system, but the `signal` error seems really strange. Do you get the same error if you run this code with `texlua`?

```
if assert(io.popen("zip -v","r"):close()) then
  print("zip found")
else
  print("zip not found")
end
```

**Comment by michal-h21** [comment]
I've made a change in `tex4ebook-exec_epub.lua` that should hopefully fix this issue.
