### ISSUE TITLE
tex4ebook transform equations into images even with epub3.

### ISSUE THREAD

**Issue by ChinouneMehdi** [michal-h21/tex4ebook#54]
tex4ebook transform equations into images even with epub3 where it is supposed to transform them as mathmal.
```Tex
\documentclass[12pt,a4paper,oneside]{article}
\usepackage[utf8]{inputenc}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{physics}

\title{Example of LaTeX}
\author{M. Chinoune}

\begin{document}

\section{Section1}

Equation 1
\begin{equation}
H\Psi(\vec{r}) = E \Psi(\vec{r})
\end{equation}

Equation inside text $V(\vec{r}_1,\vec{r_2})$, Equation 2 :
\begin{equation}
\qty( -\dfrac{\hbar^2}{2m_1}{\vec{\nabla}_1}^2-\dfrac{\hbar^2}{2m_2}{\vec{\nabla}_2}^2 +V(\vec{r}_1,\vec{r}_2) ) \Psi(\vec{r}_1,\vec{r}_2) = E \Psi(\vec{r}_1,\vec{r}_2)
\end{equation}


Equation 3:
\begin{equation}
\qty( {\vec{\nabla}}^2 +k_0^2 ) \Psi(\vec{r}) = 0
\end{equation}


\end{document}
```
`htlatex file.tex` produce html file with images.
`htlatex file.tex "xhtml, mathml" ` transform them to mathml.
`tex4ebook -f epub3 file.tex` produce an ebook with images.
```Shell
java -jar epubcheck.jar file.epub
FATAL(PKG-008): report.epub/OEBPS/content.opf(-1,-1): Unable to read file 'OEBPS/content.opf'.
ERROR(OPF-001): report.epub/OEBPS/content.opf(-1,-1): There was an error when parsing the EPUB version: Version not found.

Check finished with errors
Messages: 1 fatal / 1 errors / 0 warnings / 0 info

epubcheck completed
```

`tex4ebook -f epub3 file.tex "xhtml, mathml"` transform equations to mathml but I still got the same error from epubcheck

**Comment by michal-h21** [comment]
`tex4ebook` never produce MathML by default, it needs to be explicitly requested using the `mathml` option. It is possible to simplify the call to `tex4ebook` command by omitting the `xhtml` part, which is unnecessary (in contrast to `htlatex`, where it is required):

      tex4ebook -f epub3 filename.tex "mathml"

If you use the `.cfg` file, you can request `mathml` in the `\Preamble` command.

Regarding the Epubcheck errors, it is caused by a wrong `encoding` attribute in the OPF file. I've fixed that and some other issues in `tex4ebook` sources. Unfortunately, TeX Live cannot be updated at the moment, so the fix will appear only in the next TL release. You can use the development version in the mean time.

**Comment by ChinouneMehdi** [comment]
I think that MathML should be used by default with epub3, because it is one of the most important features introduced in epub3!. in addition images look very ugly comaring them to MathML. When try to use Dark them they appears ar rectangles with white background.
I use MikTeX, so I will get the new release soon.

**Comment by michal-h21** [comment]
The problem is that it would be difficult to choose a different Math output if MathML is selected by default, as lot of things  is redefined  when it is loaded. I agree that pictures are not optimal solution for math, but there are other options, like [precompiled MathJax](https://www.kodymirus.cz/samples/mathjaxnode/maths.html).

Anyway, you can select the MathML output for your compilation with the following `.tex4ebook` configuration file:

```
if settings.format == "epub3" then
  settings_add {
   tex4ht_sty_par =",mathml",
  }
end
```
