### ISSUE TITLE
Table of contents: Clicking links leads to wrong sections

### ISSUE THREAD

**Issue by DianaKoenraadt** [michal-h21/tex4ebook#79]
Using the text4ebook.zip file as template, I created a document.
When I generate the epub file and open it with Kindle Previewer, the table of contents does not work properly. For some links in the table of contents, I'm lead to the correct section. But some lead to entirely different sections.

**Comment by michal-h21** [comment]
Can you please post a minimal example document that shows this behaviour?

**Comment by DianaKoenraadt** [comment]
I've found that the problem exists in the default tex4ebook.zip package. Building an `epub3` fie and then opening with Kindle Previewer. It's really interesting. If, forexample, you click on section 4.2 you're led to section 4.1 instead. Unless you click on the line underlining the link itself. On second thought I think it's a Kindle Previewer issue, but I can't confirm this because I have no other method of inspecting the epub3 file at my disposal at the moment.

**Comment by michal-h21** [comment]
Ah, so this happens when you compile `tex4ebook-doc.tex`? Do you have this issue with TOC that is part of the ebook text, or with the TOC that is provided by Kindle Previewer? These two are different.

**Comment by DianaKoenraadt** [comment]
Hey, thanks for the reply. I don't know what you mean by a Kindle generated TOC. I use `\tableofcontents`, if that's what you mean. (It's really **exactly** the zip file as provided.)

**Comment by michal-h21** [comment]
I mean the bookmarks that readers display, they usually have a special button for that. I don't know about Kindle Previewer, but I think it has it too.

Anyway, do you also use development version of `make4ht`? If yes, it can be caused by one of the new experimental features. I've just fixed it, hopefully. Try to update `make4ht`, and use 

     tex4ebook tex4ebook-doc.tex "notoc"

It should prevent TOC from pointing to wrong location. If you don't use the development version of `make4ht`, then it is probably just issue in Kindle Previewer.

**Comment by DianaKoenraadt** [comment]
Ah, okay, so it's not the bookmark that the reader creates, as far as I can tell. It's just a regular page with the TOC.
I'm not using the development version of make4ht. So then it's probably a bug in Kindle Previewer.

**Comment by michal-h21** [comment]
Yes, in this case it seems so. Or I just cannot reproduce it.
