### ISSUE TITLE
Output Directory & Cleaning Temporary Files

### ISSUE THREAD

**Issue by Markyparky56** [michal-h21/tex4ebook#80]
I can't be sure if my inexperience with the toolchains used here is tripping me up or not, but I'm struggling to configure tex4ebook to operate in such a way that it doesn't vomit xhtml files all over my working directory. 

I have a LaTeX project with 30+ .tex files. I use VS Code + the latex-workshop extension to manage and edit everything. Everything seems to play nicely, I can kick off a tex4ebook command via a workshop recipe, _except_ tex4ebook generates upwards of 60 files that don't go away once it's finished. I've had some time to poke about and see what I can do to avoid this, but while the `--output-dir` arg is accepted and works, the generated `.xhtml` files are copied not moved. I've tried tinkering with a `mk4` file, since make4ht claims to have a `Make:clean()` command which will remove temporary files, but making my `mk4` file look like

```
Make:htlatex()
Make:htlatex()
Make:htlatex()
Make:clean()
```

does not work as it appears to clean each xhtml file as they're created, which leads to the build failing. I don't understand what's going on under the hood of tex4ebook or make4ht to know how to proceed. Is there a better way to do this?

**Comment by michal-h21** [comment]
Hi Mark, the problem is that the `Make:clean()` command removes all output files once it is called. It should be used separately from the Epub generation compilation. The better way how to clean files is this:

     tex4ebook filename.tex
     make4ht -m clean filename.tex

The `-m clean` option for `make4ht` executes `Make:clean{}` and suppress all further processing. I didn't implement the clean mode to tex4ebook, but you should have make4ht installed anyway, as it is required by tex4ebook.

**Comment by Markyparky56** [comment]
Many thanks! The extra step invoking make4ht takes care of those extra files.
